### ISSUE TITLE
Normal GeoJson

### ISSUE THREAD

**Issue by nicky508** [jimjonesbr/lod4wfs#26]
GeoJson only works through JSONP, however other WFS application provide GeoJson in a plain Json way. Would it be possible to implement a plain GeoJson way instead of the mandatory JSONP way. This makes it possible to handle LOD4WFS maps as normal WFS maps through uniform GeoJson..

**Comment by jimjonesbr** [comment]
Hello there! Thanks for reporting the issue.
I just submitted a quick fix that might solve your issue. After you update your source code, try the following request:

http://localhost:8088/lod4wfs/wfs?service=wfs&version=1.0.0&request=GetFeature&typename=fda:gb_codes&outputformat=text/javascript&format_options=geojson

Just use "**geojson**" instead of "**callback:loadgeojson**".

Let me know if it works for you. I'm still recovering from a surgery, so I'm unable to do any major change till next week.

**Comment by nicky508** [comment]
Nice, it works. Thanks, for you fast fix. Get healthy!

**Comment by jimjonesbr** [comment]
Great!
